site_name: Artas Linux Dotfiles
site_description: Yet another Aesthetic Hyprland Config
site_author: Artas Linux
site_url: https://artas-linux.github.io/dotfiles/
repo_url: https://github.com/artas-linux/dotfiles
repo_name: artas-linux/dotfiles
copyright: Copyright &copy; 2025 Artas Linux

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/artas-linux
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/artaslinux
  generator: false

theme:
  name: material
  custom_dir: docs/assets
  custom_css:
    - assets/extra.css
  logo: assets/logo.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: catppuccin-latte
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: catppuccin-mocha
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      # emoji_index: !!python/name:mkdocs_material_extensions.emoji.twemoji
      # emoji_generator: !!python/name:mkdocs_material_extensions.emoji.to_svg
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Desktop:
    - Hyprland: '#'
    - Waybar: '#'
    - Theming: '#'
  - Development:
    - Neovim: '#'
    - Tmux: '#'
    - Git: '#'
  - Scripts: '#'