#!/bin/bash

# Apps
# waybar &  # Already started in services
# swayosd-server &  # Already started in services
# feishin &  # Not installed

# Terminal Apps
# kitty --class btop btop &
# kitty --class nvtop nvtop &
ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false &
