---
runtime:
  threads: ~
release:
  check: true
manifest:
  enable: false
  secondary:
    - url: "https://cdn.losbroxas.org/manifest.yaml"
      enable: true
language: en-US
theme: dark
roots:
  - store: steam
    path: ~/.local/share/Steam
  - store: heroic
    path: ~/.config/heroic
  - store: steam
    path: ~/games/SteamLibrary
  - store: other
    path: ~/.local/share/dolphin-emu
  - store: other
    path: ~/.config/Ryujinx
redirects: []
backup:
  path: ~/games/gamesaves
  ignoredGames: []
  filter:
    excludeStoreScreenshots: false
    cloud:
      exclude: false
      epic: false
      gog: false
      origin: false
      steam: false
      uplay: false
    ignoredPaths: []
    ignoredRegistry: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: status
    reversed: false
  retention:
    full: 1
    differential: 0
  format:
    chosen: zip
    zip:
      compression: deflate
    compression:
      deflate:
        level: 6
      bzip2:
        level: 6
      zstd:
        level: 10
  onlyConstructive: false
restore:
  path: ~/games/gamesaves
  ignoredGames: []
  toggledPaths: {}
  toggledRegistry: {}
  sort:
    key: status
    reversed: false
  reverseRedirects: false
scan:
  showDeselectedGames: true
  showUnchangedGames: true
  showUnscannedGames: true
cloud:
  remote: ~
  path: ludusavi-backup
  synchronize: true
apps:
  rclone:
    path: /usr/bin/rclone
    arguments: "--fast-list --ignore-checksum"
customGames: []
