source = ./theme/colors.conf

$font = Maple Mono NF 10
$font-bold = Maple Mono NF 12

general {
    hide_cursor = true
}

background {
    monitor = eDP-1
    path = $HOME/.config/hypr/theme/walls/night-landscape.png
    color = $lavender

    blur_size = 2
    blur_passes = 1
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

# Password Field
input-field {
    monitor = eDP-1
    rounding = 20
    shadow_passes = 2
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.64
    dots_center = true
    inner_color = $surface0
    font_color = $text
    check_color = $yellow
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, 50
    halign = center
    valign = bottom
}

# Current Time
label {
    monitor = eDP-1
    shadow_passes = 1
    text = cmd[update:1000] echo "<big><b>$(date +"%H:%M:%S")</b></big>"
    color = $text
    font_size = 64
    font_family = $font-bold
    position = 0, -35
    halign = center
    valign = center
}

# Current Date
label {
    monitor = eDP-1
    shadow_passes = 1
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = $subtext0
    font_size = 17
    font_family = $font
    position = 0, -130
    halign = center
    valign = center
}

# Current Song
label {
    monitor = eDP-1
    text = cmd[update:1000] echo "$(~/.config/hypr/scripts/current_song)"
    shadow_passes = 1
    color = $subtext0
    font_size = 17
    font_family = $font
    position = 0, -107
    halign = center
    valign = center
}

# System Info - CPU Usage
label {
    monitor = eDP-1
    text = cmd[update:5000] echo "CPU: $(top -bn1 | grep "Cpu(s)" | awk '{print $2}' | awk -F'%' '{print $1}')%"
    shadow_passes = 1
    color = $subtext0
    font_size = 15
    font_family = $font
    position = 0, -155
    halign = center
    valign = center
}

# System Info - Memory Usage
label {
    monitor = eDP-1
    text = cmd[update:5000] echo "RAM: $(free | grep Mem | awk '{printf("%.2f%%", $3/$2 * 100.0)}')"
    shadow_passes = 1
    color = $subtext0
    font_size = 15
    font_family = $font
    position = 0, -175
    halign = center
    valign = center
}

# User Image
image {
    monitor = eDP-1
    path = $HOME/.face.icon
    shadow_passes = 2
    rounding = -1 # negative values mean circle
    size = 128
    position = 0, 100
    halign = center
    valign = center
}
