# Define your programs
$launcher = rofi -show drun
$launcher-windows = rofi -show window

$bar = waybar
$bar-toggle = killall -SIGUSR1 $bar
$bar-reload = killall $bar; $bar

$notifications-menu = swaync-client
$notifications-menu-read = $notifications-menu -C
$notifications-menu-toggle = $notifications-menu -t
$notifications-menu-disturb = $notifications-menu -d
$notifications-menu-reload = $notifications-menu -R && $notifications-menu -rs

$browser = chromium
$notetaking-app = obsidian
$terminal = ghostty
$office-suite = libreoffice
$editor = $terminal nvim
$alter-editor = vscodium
$file-manager = dolphin
$alter-file-manager = dolphin