[helpers]

[default]
depends = []

[default.files]
"GEMINI.md" = ""
Kvantum = ""
MangoHud = ""
"QtProject.conf" = ""
"Trolltech.conf" = ""
Upscayl = ""
VSCodium = ""
aaaa = ""
atuin = ""
"avante.nvim" = ""
baloofilerc = ""
bat = ""
bbbbb = ""
browser = ""
btop = ""
cava = ""
"codium-flags.conf" = ""
configstore = ""
create-next-app-nodejs = ""
crush = ""
dconf = ""
docker = ""
easyeffects = ""
elephant = ""
epiphany = ""
evolution = ""
fastfetch = ""
fd = ""
fish = ""
fits = ""
gallery-dl = ""
gh = ""
ghostty = ""
git = ""
github-copilot = ""
"glib-2.0" = ""
gnome-session = ""
go = ""
"goa-1.0" = ""
"gtk-2.0" = ""
"gtk-3.0" = ""
"gtk-4.0" = ""
gtkrc = ""
"gtkrc-2.0" = ""
hypr = ""
ibus = ""
kactivitymanagerdrc = ""
kconf_updaterc = ""
kdedefaults = ""
kdeglobals = ""
keyb = ""
kglobalshortcutsrc = ""
kitty = ""
ktimezonedrc = ""
"kwinoutputconfig.json" = ""
kwinrc = ""
lazydocker = ""
lazygit = ""
"libinput-gestures.conf" = ""
ludusavi = ""
mcphub = ""
menus = ""
"mimeapps.list" = ""
mise = ""
"monitors.xml" = ""
mouseless = ""
mpv = ""
nautilus = ""
nemo = ""
neovide = ""
npm = ""
nvim = ""
nvtop = ""
nwg-look = ""
obs-studio = ""
obsidian = ""
opencode = ""
pacman = ""
pacseek = ""
"pavucontrol.ini" = ""
plasma-localerc = ""
pulse = ""
pypoetry = ""
qBittorrent = ""
qimgv = ""
qt5ct = ""
qutebrowser = ""
rg = ""
rofi = ""
satty = ""
spicetify = ""
"spotify-flags.conf" = ""
starship = ""
swaync = ""
systemd = ""
themes = ""
tmux = ""
tmuxp = ""
tool_state = ""
topgrade = ""
"topgrade.d" = ""
totem = ""
"user-dirs.dirs" = ""
vesktop = ""
walker = ""
waybar = ""
yadm = ""
yay = ""
yazi = ""
youtube-tui = ""
zathura = ""

[default.variables]

[settings]
default_target_type = "automatic"
